/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetAllOrdersResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * A list of orders
     */
    orders?: Array<components.Order> | undefined;
};

/** @internal */
export namespace GetAllOrdersResponse$ {
    export const inboundSchema: z.ZodType<GetAllOrdersResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Orders: z.array(components.Order$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Orders === undefined ? null : { orders: v.Orders }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Orders?: Array<components.Order$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAllOrdersResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            orders: z.array(components.Order$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.orders === undefined ? null : { Orders: v.orders }),
            };
        });
}
