/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetOrderByIdRequest = {
    /**
     * ID of the order to return
     */
    orderId: number;
};

export type GetOrderByIdResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * A single order
     */
    order?: components.Order | undefined;
};

/** @internal */
export namespace GetOrderByIdRequest$ {
    export const inboundSchema: z.ZodType<GetOrderByIdRequest, z.ZodTypeDef, unknown> = z
        .object({
            orderId: z.number().int(),
        })
        .transform((v) => {
            return {
                orderId: v.orderId,
            };
        });

    export type Outbound = {
        orderId: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetOrderByIdRequest> = z
        .object({
            orderId: z.number().int(),
        })
        .transform((v) => {
            return {
                orderId: v.orderId,
            };
        });
}

/** @internal */
export namespace GetOrderByIdResponse$ {
    export const inboundSchema: z.ZodType<GetOrderByIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Order: components.Order$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Order === undefined ? null : { order: v.Order }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Order?: components.Order$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetOrderByIdResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            order: components.Order$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.order === undefined ? null : { Order: v.order }),
            };
        });
}
